<?php

/**
 * @file
 * Install, update, and uninstall functions for the sitenow_maps module.
 */

/**
 * Implements hook_field_schema().
 */
function sitenow_maps_field_schema($field) {
  switch ($field['type']) {
    case 'sitenow_map':
      $columns = array(
        'value' => array(
          'type' => 'varchar',
          'length' => '255',
          'not null' => FALSE,
        ),
      );
      break;
  }
  return array(
    'columns' => $columns,
  );
}
